name: consul
description: Basic console windowing system (TUI). Because why not.
version: 0.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
repository: https://github.com/DanielLukic/dart-kraken-api
topics: [ console, terminal, tui ]

environment:
  sdk: ^3.3.1

dependencies:
  ansi: ^0.4.2
  args: ^2.4.2
  cli_util: ^0.4.1
  console: ^4.1.0
  dart_console: ^1.2.0
  rxdart: ^0.27.7
  stream_transform: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
