name: dart_consul
description: Basic console windowing system (TUI). Because why not. Supports keyboard and mouse driven interaction.
version: 0.0.11
homepage: https://github.com/DanielLukic/consul-dart
repository: https://github.com/DanielLukic/consul-dart
topics: [ console, terminal, tui ]

environment:
  sdk: ^3.3.1

dependencies:
  ansi: ^0.4.2
  console: ^4.1.0
  dart_console: ^4.0.1
  dart_minilog: ^0.0.1
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
