name: dart_consul
description: Basic console windowing system (TUI). Because why not.
version: 0.0.1
homepage: https://github.com/DanielLukic/consul-dart
repository: https://github.com/DanielLukic/consul-dart
topics: [ console, terminal, tui ]

environment:
  sdk: ^3.3.1

dependencies:
  ansi: ^0.4.2
  console: ^4.1.0
  dart_console2: ^3.1.0
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
