name: dart_consul
description: Basic console windowing system (TUI). Because why not. Supports keyboard and mouse driven interaction.
version: 0.0.14
homepage: https://github.com/DanielLukic/consul-dart
repository: https://github.com/DanielLukic/consul-dart
topics: [ console, terminal, tui ]

environment:
  sdk: ^3.3.1

dependencies:
  ansi: ^0.4.2
  collection: ^1.18.0
  console: ^4.1.0
  dart_minilog: ^0.0.2
  rxdart: ^0.27.7
  termansi: ^0.1.1
  termlib: ^0.1.1
  termparser: ^0.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
